name: a_good_dictionary
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  camera: ^0.10.5
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_tts: ^3.6.3
  fluttertoast: ^8.2.1
  google_mlkit_text_recognition: ^0.6.0
  http: ^0.13.6
  mongo_dart: ^0.9.1
  permission_handler: ^10.2.0
  speech_to_text: ^6.1.1
  translator: ^0.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
